### ISSUE TITLE
Some packages are not exists on npmjs.com & looks suspicious

### ISSUE THREAD

**Issue by amio** [cnpm/registry.cnpmjs.org#10]
- https://cnpmjs.org/package/paypal-adder-online-2018
- https://cnpmjs.org/package/paypal-money-a-d-d-e-r-g-e-n-e-r-a-t-o-r-h-a-c-k

Is these package legitimate? How did they get published on cnpmjs.org?

**Comment by fengmk2** [comment]
They has been deleted from npmjs.com. And cnpmjs.org disable sync unpublished modules.

**Comment by amio** [comment]
Seems the synchronization delayed for days for deleted packages. Could this be faster?
